### ISSUE TITLE
[glomex-checks] implement checks like preconditions

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#280]
gcdt lookup barks for missing stack. e.g. tenkai requires needs `kumo deploy` first!

two things
* **add better error handling in this case!**
* add a precondition to gcdt-checks plugin

```
$ ENV=PROD tenkai deploy
MoinMoin sie0003a!
2018-03-31 23:59:59+00:00
2017-04-04 10:20:44.839041+00:00
ERROR: u'ops-ci'
Traceback (most recent call last):
  File "/Users/sie0003a/git/ops-ci/venv/lib/python2.7/site-packages/gcdt_plugins/glomex_lookups/lookups.py", line 54, in _resolve_lookups
    _resolve_lookups_recurse(awsclient, config[k], stackdata, lookups)
  File "/Users/sie0003a/git/ops-ci/venv/lib/python2.7/site-packages/gcdt_plugins/glomex_lookups/lookups.py", line 73, in _resolve_lookups_recurse
    _resolve_lookups_recurse(awsclient, value, stacks, lookups)
  File "/Users/sie0003a/git/ops-ci/venv/lib/python2.7/site-packages/gcdt_plugins/glomex_lookups/lookups.py", line 84, in _resolve_lookups_recurse
    stacks, lookups)
  File "/Users/sie0003a/git/ops-ci/venv/lib/python2.7/site-packages/gcdt_plugins/glomex_lookups/lookups.py", line 93, in _resolve_single_value
    return stacks[splits[2]][splits[3]]
KeyError: u'ops-ci'
(venv)`
```
opened the ticket on behalf of @webratz

**Comment by markfink** [comment]
I just rechecked and this is already working:
```
$ tenkai deploy
MoinMoin fin0007m!
Please consider an update to gcdt version: 0.1.395
ERROR: Stack 'ops-ci' does not exist.
ERROR: lookup for 'tenkai' failed: {"codedeploy": {"applicationName": "lookup:stack:ops-ci:ApplicationName", "deploymentGroupName": "lookup:stack:ops-ci:DeploymentGroupName", "deploymentConfigName": "CodeDeployDefault.AllAtOnce", "artifactsBucket": "lookup:stack:infra-dev:s3DeploymentBucket"}}
```
