### ISSUE TITLE
[glomex-checks] implement checks to prevent users from common mistakes

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#302]
this is an ongoing task to collect ideas to lift gcdt usability to the next level. If you experience a stack trace or run into an issue twice please let us know and share with us:

[x] lookup for non-existing stack
[x] VPN connection
[x] old virtualenv version
[x] empty config - no config-reader plugin or no config file
[ ] 
[ ]

**Comment by webratz** [comment]
i think while adding the support for `PYTHONIOENCODING` something went wrong:

When `PYTHONIOENCODING` is unset the `glomex-checks` plugin raises a stacktrace. imho it should output a useful warning to the user.
You can test that by using `unset PYTHONIOENCODING`

```
$ ENV=dev kumo preview
Traceback (most recent call last):
  File "/Users/sie0003a/git/ops-shared-alb/infrastructure/venv/bin/kumo", line 11, in <module>
    sys.exit(main())
  File "/Users/sie0003a/git/ops-shared-alb/infrastructure/venv/lib/python2.7/site-packages/gcdt/kumo_main.py", line 149, in main
    sys.exit(gcdt_lifecycle.main(DOC, 'kumo'))
  File "/Users/sie0003a/git/ops-shared-alb/infrastructure/venv/lib/python2.7/site-packages/gcdt/gcdt_lifecycle.py", line 201, in main
    return lifecycle(awsclient, env, tool, command, arguments)
  File "/Users/sie0003a/git/ops-shared-alb/infrastructure/venv/lib/python2.7/site-packages/gcdt/gcdt_lifecycle.py", line 64, in lifecycle
    gcdt_signals.initialized.send(context)
  File "/Users/sie0003a/git/ops-shared-alb/infrastructure/venv/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/Users/sie0003a/git/ops-shared-alb/infrastructure/venv/lib/python2.7/site-packages/glomex_checks/checks.py", line 91, in check_pythonioencoding
    encoding = os.environ['PYTHONIOENCODING']
  File "/Users/sie0003a/git/ops-shared-alb/infrastructure/venv/bin/../lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: u'PYTHONIOENCODING'
```

**Comment by markfink** [comment]
@webratz shit! I am on it. well spotted. thanks
