### ISSUE TITLE
Do not fail when pypi is down

### ISSUE THREAD

**Issue by webratz** [glomex/gcdt#313]
When running a normal `tenkai deploy` an pypi is not availlable the whole command fails.
Expected behaviour would be a short warning and then proceeding without the version check.
```
$ ENV=dev tenkai deploy
MoinMoin sie0003a!
Traceback (most recent call last):
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/bin/tenkai", line 11, in <module>
    sys.exit(main())
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/gcdt/tenkai_main.py", line 78, in main
    dispatch_only=['version'])
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/gcdt/gcdt_lifecycle.py", line 178, in main
    return lifecycle(awsclient, env, tool, command, arguments)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/gcdt/gcdt_lifecycle.py", line 65, in lifecycle
    check_gcdt_update()
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/gcdt/utils.py", line 186, in check_gcdt_update
    inst_version, latest_version = get_package_versions('gcdt')
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/gcdt/package_utils.py", line 40, in get_package_versions
    dist = next(dists)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/commands/list.py", line 203, in iter_packages_latest_infos
    all_candidates = finder.find_all_candidates(dist.key)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Users/sie0003a/git/ops-examples/sample-service/infrastructure/venv/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 482, in send
    raise RetryError(e, request=request)
pip._vendor.requests.exceptions.RetryError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/gcdt/ (Caused by ResponseError('too many 503 error responses',))
(venv)
```

currently installed packages
```
appdirs==1.4.3
args==0.1.0
awacs==0.6.0
ba==0.1.15
blinker==1.4
botocore==1.5.71
certifi==2017.4.17
chardet==3.0.4
clint==0.5.1
cowpy==1.0.1
datadog==0.13.0
dateparser==0.6.0
decorator==4.0.11
docopt==0.6.2
docutils==0.13.1
funcsigs==1.0.2
futures==3.1.1
gcdt==0.1.403
gcdt-bundler==0.0.1343
gcdt-config-reader==0.0.16
gcdt-datadog-integration==0.0.14
gcdt-gen-serverless==0.0.8
gcdt-gru==0.6.1
gcdt-lookups==0.0.16
gcdt-plugins==0.0.13
gcdt-slack-integration==0.0.13
glomex-checks==0.0.4
glomex-config-reader==0.0.17
humanize==0.5.1
idna==2.5
jmespath==0.9.3
lambda-packages==0.15.1
maya==0.3.2
packaging==16.8
pathlib2==2.3.0
pathspec==0.5.2
pendulum==1.2.4
prompt-toolkit==1.0.14
pybars3==0.9.1
pycrypto==2.6.1
Pygments==2.2.0
pyhocon==0.3.35
PyMeta3==0.5.1
pyparsing==2.2.0
pyspin==1.0.2
python-dateutil==2.6.0
pytz==2017.2
pytzdata==2017.2
regex==2017.6.7
requests==2.18.1
ruamel.ordereddict==0.4.9
ruamel.yaml==0.15.15
s3transfer==0.1.10
scandir==1.5
semver==2.7.7
simplejson==3.11.1
six==1.10.0
tabulate==0.7.5
tqdm==4.14.0
troposphere==1.9.4
tzlocal==1.4
urllib3==1.21.1
virtualenv==15.1.0
wcwidth==0.1.7
whaaaaat==0.5.2
```

**Comment by markfink** [comment]
please do not use `gcdt-plugins` it is incompatible

**Comment by webratz** [comment]
Seems like that is left somewhere in my venv I used. Can we create a new version of `gcdt-plugins` that tells users of newer gcdt versions that it isn't compatible anymore?
