### ISSUE TITLE
[all] add stacktrace to '-v' option

### ISSUE THREAD

**Issue by markfink** [glomex/gcdt#361]
I am opening this ticket on behalf of @Tonkonozhenko 

Hi @here

I have a bug with kumo:
```
ERROR: 'ascii' codec can't encode characters in position 0-47: ordinal not in range(128)
```

I got it several times and it depends on where I run script, e.g. it works well in Iterm2, but does not work on jenkins and in rubymine

Mark Fink 
[10:03 AM] 
Hi, need more info

[10:06] 
* what are you trying to do (which command)
* which version are you using (post output of 'gcdt version')
* have you tried to run the command with the '-v' option? and what was the output

Alex Tonkonozhenko 
[10:09 AM] 
```
(default) ➜  cloudformation git:(at/pb-700) ✗ gcdt version
WARNING: Please consider an update to gcdt version: 0.1.430
gcdt version 0.1.423
gcdt plugins:
 * gcdt-config-reader version 0.0.17
 * gcdt-bundler version 0.0.1343
 * gcdt-say-hello version 0.0.14
 * gcdt-slack-integration version 0.0.15
 * gcdt-datadog-integration version 0.0.16
 * gcdt-lookups version 0.0.18
(default) ➜  cloudformation git:(at/pb-700) ✗ APP_NAME=api-keys AWS_PROFILE=superuser-portal-dev ENV=qa DEPLOYMENT_ENV=qa IMAGE_TAG=f769c87 kumo deploy 
MoinMoin alex!
WARNING: Please consider an update to gcdt version: 0.1.430
2017-08-21 23:59:59+00:00
2017-08-10 08:09:00.789113+00:00
Did not find ImageTag in local config file
Did not find AppName in local config file
Did not find DeploymentEnv in local config file
Did not find multiAZ in local config file
Did not find RedisInstanceType in local config file
Did not find ELBDNSName in local config file
Traceback (most recent call last):
  File "/Users/alex/.pythons/default/lib/python2.7/site-packages/gcdt/gcdt_lifecycle.py", line 139, in lifecycle
    config=config.get(tool, {}))
  File "/Users/alex/.pythons/default/lib/python2.7/site-packages/gcdt/gcdt_cmd_dispatcher.py", line 95, in dispatch
    exit_code = func(*args, **kwargs)
  File "/Users/alex/.pythons/default/lib/python2.7/site-packages/gcdt/kumo_main.py", line 82, in deploy_cmd
    if get_parameter_diff(awsclient, conf):
  File "/Users/alex/.pythons/default/lib/python2.7/site-packages/gcdt/kumo_core.py", line 117, in get_parameter_diff
    print(tabulate(table, tablefmt='fancy_grid'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-47: ordinal not in range(128)
ERROR: 'ascii' codec can't encode characters in position 0-47: ordinal not in range(128)
ERROR: 'ascii' codec can't encode characters in position 0-47: ordinal not in range(128)
```

[10:09] 
I modified gcdt_lifecycle little bit to print stacktrace

Alex Tonkonozhenko 
[12:13 PM] 
@mark

Fixed with `export PYTHONIOENCODING=UTF-8`

[12:13] 
cc @maksym.sotnikov ^

Mark Fink 
[12:37 PM] 
awesome @alex.tonkonozhenko, alternatively you could have just used the '-v' option like I recommended

Alex Tonkonozhenko 
[12:41 PM] 
-v option does not help at all, it just outputs exception message without stacktrace

**Comment by markfink** [comment]
fixed that with 0.1.441
